var data = {
    "category": [{
        "category_name": "美食",
        "secondary_category": [{
            "category_name": "江浙菜"
        }, {
            "category_name": "粤菜"
        }, {
            "category_name": "川菜"
        }, {
            "category_name": "湘菜"
        }, {
            "category_name": "东北菜"
        }, {
            "category_name": "徽菜"
        }, {
            "category_name": "闽菜"
        }, {
            "category_name": "鲁菜"
        }, {
            "category_name": "台湾菜"
        }, {
            "category_name": "西北菜"
        }, {
            "category_name": "东南亚菜"
        }, {
            "category_name": "西餐"
        }, {
            "category_name": "日韩菜"
        }, {
            "category_name": "火锅"
        }, {
            "category_name": "清真菜"
        }, {
            "category_name": "小吃快餐"
        }, {
            "category_name": "海鲜"
        }, {
            "category_name": "烧烤"
        }, {
            "category_name": "自助餐"
        }, {
            "category_name": "面包甜点"
        }, {
            "category_name": "茶餐厅"
        }, {
            "category_name": "其它美食"
        }]
    }, {
        "category_name": "基础设施",
        "secondary_category": [{
            "category_name": "交通设施"
        }, {
            "category_name": "公共设施"
        }, {
            "category_name": "道路附属"
        }, {
            "category_name": "其它基础设施"
        }]
    }, {
        "category_name": "医疗保健",
        "secondary_category": [{
            "category_name": "专科医院"
        }, {
            "category_name": "综合医院"
        }, {
            "category_name": "诊所"
        }, {
            "category_name": "急救中心"
        }, {
            "category_name": "药房药店"
        }, {
            "category_name": "疾病预防"
        }, {
            "category_name": "其它医疗保健"
        }]
    }, {
        "category_name": "生活服务",
        "secondary_category": [{
            "category_name": "家政"
        }, {
            "category_name": "宠物服务"
        }, {
            "category_name": "旅行社"
        }, {
            "category_name": "摄影冲印"
        }, {
            "category_name": "洗衣店"
        }, {
            "category_name": "票务代售"
        }, {
            "category_name": "邮局速递"
        }, {
            "category_name": "通讯服务"
        }, {
            "category_name": "彩票"
        }, {
            "category_name": "报刊亭"
        }, {
            "category_name": "自来水营业厅"
        }, {
            "category_name": "电力营业厅"
        }, {
            "category_name": "教练"
        }, {
            "category_name": "生活服务场所"
        }, {
            "category_name": "信息咨询中心"
        }, {
            "category_name": "招聘求职"
        }, {
            "category_name": "中介机构"
        }, {
            "category_name": "事务所"
        }, {
            "category_name": "丧葬"
        }, {
            "category_name": "废品收购站"
        }, {
            "category_name": "福利院养老院"
        }, {
            "category_name": "测字风水"
        }, {
            "category_name": "家装"
        }, {
            "category_name": "其它生活服务"
        }]
    }, {
        "category_name": "休闲娱乐",
        "secondary_category": [{
            "category_name": " 洗浴推拿足疗"
        }, {
            "category_name": "KTV"
        }, {
            "category_name": "酒吧"
        }, {
            "category_name": "咖啡厅"
        }, {
            "category_name": "茶馆"
        }, {
            "category_name": "电影院"
        }, {
            "category_name": "棋牌游戏"
        }, {
            "category_name": "夜总会"
        }, {
            "category_name": "剧场音乐厅"
        }, {
            "category_name": "度假疗养"
        }, {
            "category_name": "户外活动"
        }, {
            "category_name": "网吧"
        }, {
            "category_name": "迪厅"
        }, {
            "category_name": "演出票务"
        }, {
            "category_name": "其它娱乐休闲"
        }]
    }, {
        "category_name": "购物",
        "secondary_category": [{
            "category_name": "综合商场"
        }, {
            "category_name": "便利店"
        }, {
            "category_name": "超市"
        }, {
            "category_name": "花鸟鱼虫"
        }, {
            "category_name": "家具家居建材"
        }, {
            "category_name": "体育户外"
        }, {
            "category_name": "服饰鞋包"
        }, {
            "category_name": "图书音像"
        }, {
            "category_name": "眼镜店"
        }, {
            "category_name": "母婴儿童"
        }, {
            "category_name": "珠宝饰品"
        }, {
            "category_name": "化妆品"
        }, {
            "category_name": "食品烟酒"
        }, {
            "category_name": "数码家电"
        }, {
            "category_name": "农贸市场"
        }, {
            "category_name": "小商品市场"
        }, {
            "category_name": "旧货市场"
        }, {
            "category_name": "商业步行街"
        }, {
            "category_name": "礼品"
        }, {
            "category_name": "摄影器材"
        }, {
            "category_name": "钟表店"
        }, {
            "category_name": "拍卖典当行"
        }, {
            "category_name": "古玩字画"
        }, {
            "category_name": "自行车专卖"
        }, {
            "category_name": "文化用品"
        }, {
            "category_name": "药店"
        }, {
            "category_name": "品牌折扣店"
        }, {
            "category_name": "自动售货机"
        }, {
            "category_name": "其它购物"
        }]
    }, {
        "category_name": "运动健身",
        "secondary_category": [{
            "category_name": "健身中心"
        }, {
            "category_name": "游泳馆"
        }, {
            "category_name": "瑜伽"
        }, {
            "category_name": "羽毛球馆"
        }, {
            "category_name": "乒乓球馆"
        }, {
            "category_name": "篮球场"
        }, {
            "category_name": "足球场"
        }, {
            "category_name": "壁球场"
        }, {
            "category_name": "马场"
        }, {
            "category_name": "高尔夫场"
        }, {
            "category_name": "保龄球馆"
        }, {
            "category_name": "溜冰"
        }, {
            "category_name": "跆拳道"
        }, {
            "category_name": "海滨浴场"
        }, {
            "category_name": "网球场"
        }, {
            "category_name": "橄榄球"
        }, {
            "category_name": "台球馆"
        }, {
            "category_name": "滑雪"
        }, {
            "category_name": "舞蹈"
        }, {
            "category_name": "攀岩馆"
        }, {
            "category_name": "射箭馆"
        }, {
            "category_name": "综合体育场馆"
        }, {
            "category_name": "其它运动健身"
        }]
    }, {
        "category_name": "汽车",
        "secondary_category": [{
            "category_name": "加油站"
        }, {
            "category_name": "停车场"
        }, {
            "category_name": "4S店"
        }, {
            "category_name": "汽车维修"
        }, {
            "category_name": "驾校"
        }, {
            "category_name": "汽车租赁"
        }, {
            "category_name": "汽车配件销售"
        }, {
            "category_name": "汽车保险"
        }, {
            "category_name": "摩托车"
        }, {
            "category_name": "汽车养护"
        }, {
            "category_name": "洗车场"
        }, {
            "category_name": "汽车俱 乐部"
        }, {
            "category_name": "汽车救援"
        }, {
            "category_name": "二手车交易市场"
        }, {
            "category_name": "车辆管理机构"
        }, {
            "category_name": "其它汽车"
        }]
    }, {
        "category_name": "酒店宾馆",
        "secondary_category": [{
            "category_name": "星级酒店"
        }, {
            "category_name": "经济型酒店"
        }, {
            "category_name": "公寓式酒店"
        }, {
            "category_name": "度假村"
        }, {
            "category_name": "农家院"
        }, {
            "category_name": "青年旅社"
        }, {
            "category_name": "酒店宾馆"
        }, {
            "category_name": "旅馆招待所"
        }, {
            "category_name": "其它酒店宾馆"
        }]
    }, {
        "category_name": "旅游景点",
        "secondary_category": [{
            "category_name": "公园"
        }, {
            "category_name": " 其它旅游景点"
        }, {
            "category_name": "风景名胜"
        }, {
            "category_name": "植物园"
        }, {
            "category_name": "动物园"
        }, {
            "category_name": "水族馆"
        }, {
            "category_name": "城市广场"
        }, {
            "category_name": "世界遗产"
        }, {
            "category_name": "国家级景点"
        }, {
            "category_name": "省级景点"
        }, {
            "category_name": "纪念馆"
        }, {
            "category_name": "寺庙道观"
        }, {
            "category_name": "教堂"
        }, {
            "category_name": "海滩"
        }]
    }, {
        "category_name": "文化场馆",
        "secondary_category": [{
            "category_name": "博物馆"
        }, {
            "category_name": "图书馆"
        }, {
            "category_name": "美术馆"
        }, {
            "category_name": "展览馆"
        }, {
            "category_name": "科技馆"
        }, {
            "category_name": "天文馆"
        }, {
            "category_name": "档案馆"
        }, {
            "category_name": "文化宫"
        }, {
            "category_name": "会展中心"
        }, {
            "category_name": "其它文化场馆"
        }]
    }, {
        "category_name": "教育学校",
        "secondary_category": [{
            "category_name": "小学"
        }, {
            "category_name": " 幼儿园"
        }, {
            "category_name": "其它教育学校"
        }, {
            "category_name": "培训"
        }, {
            "category_name": "大学"
        }, {
            "category_name": "中学"
        }, {
            "category_name": "职业技术学校"
        }, {
            "category_name": "成人教育"
        }]
    }, {
        "category_name": "银行金融",
        "secondary_category": [{
            "category_name": "银行"
        }, {
            "category_name": "自动提款机"
        }, {
            "category_name": "保险公司"
        }, {
            "category_name": "证券公司"
        }, {
            "category_name": "财务公司"
        }, {
            "category_name": "其它银行金融"
        }]
    }, {
        "category_name": "地名地址",
        "secondary_category": [{
            "category_name": "交通地名"
        }, {
            "category_name": "地名地址信息"
        }, {
            "category_name": "道路名"
        }, {
            "category_name": "自然地名"
        }, {
            "category_name": "行政地名"
        }, {
            "category_name": "门牌信息"
        }, {
            "category_name": "其它地名地址"
        }]
    }, {
        "category_name": "房产小区",
        "secondary_category": [{
            "category_name": "住宅区"
        }, {
            "category_name": "产业园区"
        }, {
            "category_name": "商务楼宇"
        }, {
            "category_name": "其它房产小区"
        }]
    }, {
        "category_name": "丽人",
        "secondary_category": [{
            "category_name": " 美发"
        }, {
            "category_name": "美容"
        }, {
            "category_name": "SPA"
        }, {
            "category_name": "瘦身纤体"
        }, {
            "category_name": "美甲"
        }, {
            "category_name": "写真"
        }, {
            "category_name": "其它"
        }]
    }, {
        "category_name": "结婚",
        "secondary_category": [{
            "category_name": "婚纱摄 影"
        }, {
            "category_name": "婚宴"
        }, {
            "category_name": "婚戒首饰"
        }, {
            "category_name": "婚纱礼服"
        }, {
            "category_name": "婚庆公司"
        }, {
            "category_name": "彩妆 造型"
        }, {
            "category_name": "司仪主持"
        }, {
            "category_name": "婚礼跟拍"
        }, {
            "category_name": "婚车租赁"
        }, {
            "category_name": "婚礼小商品"
        }, {
            "category_name": "婚房装修"
        }, {
            "category_name": "其它"
        }]
    }, {
        "category_name": "亲子",
        "secondary_category": [{
            "category_name": "亲子摄影"
        }, {
            "category_name": "亲子游乐"
        }, {
            "category_name": "亲子购物"
        }, {
            "category_name": "孕产护理"
        }]
    }, {
        "category_name": "公司企业",
        "secondary_category": [{
            "category_name": "农林牧渔基地"
        }, {
            "category_name": "企业/工厂"
        }, {
            "category_name": "其它公司企业"
        }]
    }, {
        "category_name": "机构团体",
        "secondary_category": [{
            "category_name": "公检法机构"
        }, {
            "category_name": "外国机构"
        }, {
            "category_name": "工商税务机构"
        }, {
            "category_name": "政府机关"
        }, {
            "category_name": "民主党派"
        }, {
            "category_name": "社会团体"
        }, {
            "category_name": "传媒机构"
        }, {
            "category_name": "文艺团体"
        }, {
            "category_name": "科研机构"
        }, {
            "category_name": "其它机构团体"
        }]
    }]
};
